version: '3.2'

volumes:
  myonlyfun_db:

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: myonlyfun
    volumes:
      - myonlyfun_db:/data
    ports:
      - 5432:5432
